# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crypto_exchanges' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Pods for crypto_exchanges

  target 'crypto_exchangesTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Nimble'
    pod 'Nimble-Snapshots'
    pod 'Quick'
  end

  target 'crypto_exchangesUITests' do
    # Pods for testing
  end

end
